"""Cacheable shared UI assets that are generated by Python render helpers."""

from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import Response

from sales_support_agent.services.admin_nav import render_agent_nav_css


router = APIRouter(include_in_schema=False)


@router.get("/admin/assets/navigation.css")
def navigation_stylesheet() -> Response:
    """Serve shared navigation CSS once instead of embedding it per page."""
    return Response(
        content=render_agent_nav_css(),
        media_type="text/css",
        headers={"Cache-Control": "public, max-age=31536000, immutable"},
    )
